### ISSUE TITLE
It keeps telling me to Install BepInEx 4, but I already did that

### ISSUE THREAD

**Issue by JohnnyGAB1108** [kkdevs/Patchwork#10]
It keeps telling me to Install BepInEx 4, but I already did that, what else can I do to get it working?

**Comment by ezdiy** [comment]
You need to uninstall bep 3 properly. Remove, if present, bepinex.dll, 0harmony.dll from Koikatu_Data/Managed and Charastudio_Data/Managed.

read https://github.com/BepInEx/BepInEx/wiki/Migration carefuly

**Comment by ezdiy** [comment]
no resp
