### ISSUE TITLE
IPA mod error

### ISSUE THREAD

**Issue by RedGrundy** [kkdevs/Patchwork#11]
The pushup bra mod wasn't loading properly with patchwork 11v2 and after gleaming the output_log I found it was throwing up an exception while playing the game

MissingMethodException: Method not found: 'ListInfoBase.get_Name'.
  at KK_Kiyase.KK_Kiyase.UpdateFemale () [0x00000] in <filename unknown>:0 
  at KK_Kiyase.KK_Kiyase.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2172483/output_log.txt)

**Comment by ezdiy** [comment]
should work in mk12 now, please check

**Comment by RedGrundy** [comment]
I can confirm it's working now
