### ISSUE TITLE
Launching Studio fails with message to upgrade to Bep4. Already done.

### ISSUE THREAD

**Issue by enkephalin07** [kkdevs/Patchwork#16]
I don't believe I have anything of Bep3 remaining in my directories, but if I do it hasn't interfered with Bep4. As far as Bep4 is concerned, I'm as updated as I need to be.

**Comment by ezdiy** [comment]
Remove bepinex.dll and 0harmony.dll from Charastudio_Data/Managed.

**Comment by enkephalin07** [comment]
Got it, working now.
