### ISSUE TITLE
Saved cards unreadable by other 3rd party apps

### ISSUE THREAD

**Issue by enkephalin07** [kkdevs/Patchwork#17]
It looks like patchwork is saving cards with some kind of compression, but I don't see any option to turn it off. This makes me concerned about the compatibility of games saved with patchwork as well.

**Comment by ezdiy** [comment]
Disable 'Encode face as jpeg'. jpeg is compatible with vanilla game, but indeed may break tools which expect faces to be png only.

**Comment by enkephalin07** [comment]
ty, works fine now.
