### ISSUE TITLE
[Abient Occlusion]

### ISSUE THREAD

**Issue by laylajung** [kkdevs/Patchwork#2]
Sorry for contacting you here but I do not know where else to message you.
If possible, could you add an option to forcefully turn off [Abient Occlusion] as it remains on in the main game even when turned off. Turning it off only works in the studio and character creation only.

**Comment by ezdiy** [comment]
The in game config option seems to work - uncheck F1->AO checkbox, and FPS goes up by 10-20% if your GPU is maxed. I suspect you mean environment ie the level as such? That one seems to be baked into the static lightmap ("hard shadows"). You can disable that now by choosing the grossly misnamed select box 'dynamic shadows' to off, but you lose all "hard" environmental lighting in the process, too.

**Comment by laylajung** [comment]
Here is an example: 
1: https://prnt.sc/jowpqy 
2: https://prnt.sc/jowq5i
If you rather chat privately.
Discord: Layla Jung#4542

**Comment by ezdiy** [comment]
mk6 now allows overriding global effect shaders
