### ISSUE TITLE
Height slider (for male) doesn't work after mk13 release

### ISSUE THREAD

**Issue by gizosate** [kkdevs/Patchwork#20]
Height slider doesn't work after mk13 release. But my game crashes with mk13 release, when I start a new game or load existing one. 

mk15 works, except height slider stopped working.

Hope you will fix it.

thanks

**Comment by ezdiy** [comment]
Try disabling `Advanced->Performance->Async chara maker loading` (before launching the game) and see where that takes you. If it doesnt help, try to disable everything in that section. If still of no help, enable `[SPAM]` in logging section, run maker, change slider, exit, and post resulting Koikatu_Data/output_log.txt, it should contain hint what goes wrong.

Final suspect might be uncensor, so try removing that too.

**Comment by gizosate** [comment]
Hi, sorry, I forgot to clarify that height slider doesn't work only for male (corrected subj).  
Tried to disable Async and everything in that section, still doesn't work.
Tried to repeat issue in clean japanese game without mods with latest DLC cdp0629opc_all, but still height slider for male doesn't work.
When I change height, noting happens, and after I switch to another tab and back to body, height resets back to 60, so it just locked on 60 it seems.

Attached all text from console with SPAM option enabled.
[SPAM.txt](https://github.com/kkdevs/Patchwork/files/2221121/SPAM.txt)

**Comment by ezdiy** [comment]
Indeed knowing it's male slider helps. mk15v6.

**Comment by gizosate** [comment]
Tested in mk16 and it works now, thank you!
