### ISSUE TITLE
whitescreen on visit gf

### ISSUE THREAD

**Issue by buggmet** [kkdevs/Patchwork#22]
the games stays in white screen if your gf is visiting you in morning.

**Comment by ezdiy** [comment]
post output log the next time that that happens (or if you still have it. but old log is deleted if you start the game again...).

**Comment by buggmet** [comment]
7/27 update i think fix the problem in 16v2 patchwork also the hsubs when offline hangs on h scene so disabling it fix h scene hang, so far 17v3 has no problems at all for now.
