### ISSUE TITLE
Slider -min/+max not applying to certain sliders that still see effects below 0/over 100

### ISSUE THREAD

**Issue by ark-royal-91** [kkdevs/Patchwork#23]
Mainly for cloth pattern width+height, but it also affects breast softness, breast weight, and areola size. It *does* work on hair lengths, however, of which no existing ones record changes below 0 or above 100.

Not sure 100% this is a Patchwork problem, but the sliders in question do work with the same mod set while booting without Patchwork and using SliderUnlocker instead, while removing SliderUnlocker from the blacklist for Patchwork produces the same behavior as with it blacklisted.

**Comment by ezdiy** [comment]
thanks, try 16v2. there might some clamps still left somewhere.

**Comment by ark-royal-91** [comment]
Confirming all sliders seem to be behaving correctly in v2 and I'm just a clown who didn't notice I was still on v1!
