### ISSUE TITLE
[17v5] hsubs leads to null reference softlock if first H scene is with DLC personality

### ISSUE THREAD

**Issue by ark-royal-91** [kkdevs/Patchwork#26]
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2246990/output_log.txt)

Intro voice clip will play, but no others will.

Softlock occurs when entering a non-interactive state due to climax or scene change, though you can still force escape by returning to title via settings menu.

Engaging any non-DLC personality in an H scene resolves the problem the rest of the session.

**Comment by ezdiy** [comment]
thx. v6 should work. note that the subs for those wont show as those aren't actually dumped/gtled yet. workaround is to switch to jp and autotranslator.
