### ISSUE TITLE
[KKPE] Incompatibility - Settings don't appear to save or load properly

### ISSUE THREAD

**Issue by Bluhmanman** [kkdevs/Patchwork#28]
**Issue**: Prior to using Patchwork, KKPE advanced settings, such as bone weights, scales, and face morphs, would be saved, loaded, and preserved. Now with Patchwork, it's unclear as to whether scenes saved have their KKPE data prerserved, and scenes that prior loaded with KKPE settings now load without them.

[output_log.txt](https://github.com/kkdevs/Patchwork/files/2252726/output_log.txt)

My output log. Just doing a cursory search through the log reveals KKPE apparently trying to reference parts of characters before they exist in the scene? Turning off all other DLLs, as well as disabling all optimizations, however, does not appear to have remedied the issue.

**Reproduction steps:** Run studio with all DLLs disabled. With a scene verified to work with KKPE, attempt to load the scene. The end result of loading should be the scene loaded without any of the modifications or data included from the KKPE mod.

Attached below is a sample studio scene that has KKPE data.
![2018_0718_2034_18_212](https://user-images.githubusercontent.com/22921549/43572799-f7e8f8be-9605-11e8-9925-3ebcda76d18b.png)

In a proper KKPE load, the wolfman should have crooked legs and larger hands, while the knight should have slightly larger hands as well. If reproduced, these two characters will have normal proportions.

as an aside my saves also don't seem to be preserving line of sight settings either, nor does line of sight appear to work from the get-go in my version of Patchwork. (edit: confirmed to be due to a specific body mod used.)

I am using mk17v6.

**Comment by Bluhmanman** [comment]
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2254800/output_log.txt)

Attempt at loading KKPE in studio without:
- Any mods
- Any scripts
- Any other DLLs
- Any patchwork optimizations

I'm still getting errors referring to KKPE. This time, the dump seems to indicate that functions of the KPPE mod are getting culled by some kind of memory-reduction measure.

**Comment by Bluhmanman** [comment]
After closer look at save files made after using KKPE through patchwork I can confirm that KKPE data is also not saved inside scene images either.

Here is a dump where I do the following actions:

- Open Studio via Patchwork
- Create a default male character
- Use KKPE to scale the character's hands and feet to double size
- Save the file:
![2018_0802_1411_43_958](https://user-images.githubusercontent.com/22921549/43605591-6f0c1504-965e-11e8-858b-1464d365eb46.png)
- Load the file.
- File now has normal proportions

Here's the log of these operations:
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2254856/output_log.txt)
The log shows no errors pertaining to KKPE specifically, indicating that KKPE data isn't even saved to the file to begin with. If you look at the save image included, you'll also see there are no lines that indicate KKPE features are included in the save file.

**Comment by ezdiy** [comment]
thanks. should work with v8 now. the other errors are (hopefuly) harmless.

**Comment by Bluhmanman** [comment]
Confirmed fixed. Thank you!
