### ISSUE TITLE
Loading Screen stuck 50% during clubroom screens

### ISSUE THREAD

**Issue by wailingnoob** [kkdevs/Patchwork#3]
Any interaction with the Koikatu club interaction points ends up with a 50% loading freeze. Unable to check club progress or call members with patchwork but works fine with regular game exe.

**Comment by ezdiy** [comment]
Thanks for report, added to known issues in the release notes. Use mk5v5 for now if this is a showstopper. It's related to bundle loading rewrite done in mk6 and might take a while to fix this.

Edit: fixed the issue, try mk6v4.
