### ISSUE TITLE
[Studio] Standard Settings not taking Blush or 'Show Cock' options, and other issues with Studio Character settings.

### ISSUE THREAD

**Issue by Bluhmanman** [kkdevs/Patchwork#30]
**Issues:**
- Characters in studio do not adopt blush settings while Patchwork is enabled.
- Characters with penis enabled will not show it through clothing. It still appears once both bottoms and underwear are removed, but this is not identical to how the function operates in base CharaStudio.
![image](https://user-images.githubusercontent.com/22921549/43615600-120da686-967e-11e8-92fe-eef1adab0c67.png)
- If the user defines a custom uncensor model in the patchwork launcher and checks "use these for studio characters", the line of sight function does not work.
![image](https://user-images.githubusercontent.com/22921549/43615854-47f42076-967f-11e8-9084-e49ccb48c742.png)

I doubt this helps any, but this is a log of me performing actions to: open studio, load a default male character, increase their blush settings to max, enable their penis while clothes are still on, and then changing their line-of-sight to 'adjust' and then attempting to move the LOS node around.

[output_log.txt](https://github.com/kkdevs/Patchwork/files/2255435/output_log.txt)

**Comment by ezdiy** [comment]
1. You need to enable it in game config menu. In pw, studio and game are the same thing, just with different scene. The IG settings such as this one are still respected - `<hohoAka>True</hohoAka>` in system.xml.
2. The behavior originates from changes for futa - visibility is controlled by clothing. Probably makes sense to make this behavior dependent on whether studio is running or not.
3. TBF. What happens here with imported base model from main game is that it lacks necessary parts for hand IK and eye tracking and pw plugs those on the fly (but not very accurately, hence the glitches). A sort of workaround is to enable the setting, spawn the character you need it for, uncheck. Won't work for saved scenes though.

All of these are cosmetic enough it will have to wait for mk18.
