### ISSUE TITLE
Female uncensors make character disappear

### ISSUE THREAD

**Issue by party-horse** [kkdevs/Patchwork#32]
Hi.
I can't get popular uncensors to work:
Tried to place "oo_base.unity3d" from [Kitty v0.5.zip](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/5990340-illusion-koikatu-koikatsu-%E3%82%B3%E3%82%A4%E3%82%AB%E3%83%84%EF%BC%81-mods-no-discussion-allowed?p=6053003#post6053003) into \patchwork\mod\abdata\chara\
Tried to place "mm_base.unity3d" and "oo_base.unity3d" from [moderchan's funcensor01](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/5990340-illusion-koikatu-koikatsu-%E3%82%B3%E3%82%A4%E3%82%AB%E3%83%84%EF%BC%81-mods-no-discussion-allowed?p=6048052#post6048052) into \patchwork\mod\abdata\chara\
in both cases female character is not visible in maker and during test run in Free-H.

The only uncensor that works, is the one from [KoikPlugins](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/5990340-illusion-koikatu-koikatsu-%E3%82%B3%E3%82%A4%E3%82%AB%E3%83%84%EF%BC%81-mods-no-discussion-allowed?p=6058995#post6058995) mod, I just unpacked in into game's \abdata\chara\ dir

Game is patched with IPA (in order to run KoikPlugins mod) and using BepInEx framework, its plugins and Sideloader Modpack mods at the same time, which is only possible to achieve using your launcher.

Any idea why other uncensors do not work except the one from KoikPlugins mod? Is it possible for you to fix this compatibility issue(I believe) via Patchwork launcher?

Thanks

**Comment by ezdiy** [comment]
You're attempting to use unsafe (ie partial bundle) as a standard mod. Unsafe needs to be marked with + prefix, ie `+oo_base.unity3d`. Unzip script does this for you if you place the uncensor zip into Koikatu/mods.

**Comment by party-horse** [comment]
Thanks!
Actually ticking this checkbox "Load unsafe mods" helped to fix this. 
![unsafe](https://user-images.githubusercontent.com/42155164/43801549-19ec1190-9a9c-11e8-8c49-822a354be290.PNG)
I tried to put .zip into  Koikatu/mods before and files were with + prefixes, but females were still invisible.
