### ISSUE TITLE
Characters disappear  

### ISSUE THREAD

**Issue by aina00** [kkdevs/Patchwork#33]
Hi there,

I find the game cannot load the characters, I think it is because of the uncensors for both male and female as I use zipmod uncensors ([Female][Uncensor]KK_LO_pussy_v0.5 and [enk]whatsadick[ballz]4), however I cannot sure is the problem really cause by it.

I have tried open the game with load unsafe mod option mod and also without it but both aren't work.

Here is the output log(without load unsafe mod option)

[output_log.txt](https://github.com/kkdevs/Patchwork/files/2267764/output_log.txt)

and here is the one with load unsafe mod option

[output_log2.txt](https://github.com/kkdevs/Patchwork/files/2267778/output_log2.txt)

**Comment by ezdiy** [comment]
I've installed both uncensors you're using and they load fine.

In both output logs you posted oo_base indeed fails to load, but it's not very clear why.

![image](https://user-images.githubusercontent.com/1587676/43798791-f4e68c6e-9a8b-11e8-82a8-525bab5286f2.png)

the female uncensor is from uppervolta, the male one from hf patch, which is hopefuly the same as what you have.

When you search `patchwork/mod` for files named `*base.unity3d`, you should encounter the picture above. If you see more or different files, or different file sizes, it means you have different mods than you think you have.

**Comment by ezdiy** [comment]
The uncensors load fine here.

Here are the files i get:
https://www21.zippyshare.com/v/ckEto1Jk/file.html

You can try this out by unchecking the unzip script and placing only the two uncensors into mod/ with everything else removed. Most likely you have some custom versions of kk_lo, or unrelated mm_base/oo_base files.

In addition you seem to be using stale cache files, delete patchwork/cache.

**Comment by aina00** [comment]
It fixed! thanks so much!
It seems it is because there is an old version of breastbodycollider in the mod folder.
thanks so much again!
