### ISSUE TITLE
Cannot start the game after updated

### ISSUE THREAD

**Issue by aina00** [kkdevs/Patchwork#34]
Hi there,

After I updated pw to 19v4, the game freeze like this
![cvbnvc](https://user-images.githubusercontent.com/42187155/43976250-f8749e20-9d1a-11e8-8320-2369d0d6bcf9.PNG)

But after I downgraded it to 18v2, it can run normally
I can't provide a output log as the output_log file cannot open after I force closed the game(maybe it is because the game crashed before it load anything?)

**Comment by ezdiy** [comment]
Try to uncheck 'unzip' in scripts. As usual, try deleting patchwork/cache or even the whole patchwork folder.

Output log should be there, even after force close.

**Comment by aina00** [comment]
already unchecked unzip and deleting patchwork/cache or the whole patchwork folder, but still cannot start the game
Yes, Output log is there, but it seems it is broken(cannot open the file)

**Comment by ezdiy** [comment]
log out or restart computer. also try to disable all mod loading, and perhaps plugins if you have any.

**Comment by aina00** [comment]
sorry for late reply
can start the game now, seem crash with the plugin
thanks a lot
