### ISSUE TITLE
Missing textures, surfaces

### ISSUE THREAD

**Issue by enkephalin07** [kkdevs/Patchwork#4]
I've been getting a lot of this since mk6v4:
![image](https://user-images.githubusercontent.com/15174848/41265757-6d0b7808-6db9-11e8-9064-77f2afcfc740.png)
This happens after a number of character interactions, and guaranteed to happen after an H-scene. Around that time I can also expect to see girls walking around missing torsos and clothing.

Here's a zip with my patchwork.xml so you can see my settings, and Koikatu_Data/output_log.txt with a lot of RenderTexture fails, NULL textures, and errors from VRDevice which shouldn't even be operating in this environment.
[mk8v4_xml_and_output_log06112018.zip](https://github.com/kkdevs/Patchwork/files/2092289/mk8v4_xml_and_output_log06112018.zip)

**Comment by ezdiy** [comment]
```
    VRAM:     970 MB
```

Patchwork uses much more vram than vanilla game as it attempts to keep textures cached on gpu. For now, you might try unchecking 'cache assets', please tell if that changes anything. Chances are it may not, as we we skimp on telling unity to flush its own caches on character reload and that behavior is currently hardcoded. I'll add checkbox option to be closer to vanilla in that regard too for better low-end system support.

**Comment by ezdiy** [comment]
old
