### ISSUE TITLE
Dick texture missed

### ISSUE THREAD

**Issue by emris93** [kkdevs/Patchwork#5]
Hello,
I downloaded patchwork but the dick is missed texture : 
https://user-images.githubusercontent.com/40270055/41423619-4ce7bbca-6feb-11e8-91a6-3902712e9343.jpg (nsfw content)

I tested 4 differents versions : Mk5v5 Mk8v7, Mk9v1, MK9v2. 
Any idea please ?

**Comment by ezdiy** [comment]
You don't have any uncensor mods. What you see is what the game has when only mosaic is removed and body texture applied to vanilla "dickpole" mesh - thats the only thing patchwork is supposed to do - change game code, not data.

It does not contain any textures or meshes which you need to get proper uncensor.

Also, you seem to be loading a male card in female editor for some reason, which has only certain specialized uses (male-skeleton futas) and needs specialized mods to work properly.

**Comment by emris93** [comment]
hello, 
I resolve the problem but any idea to how can I have full futanari mod uncensored please ? And
I notice some problems : 
1) if I launch the game directly I have the dick perfectly and I CAN load my save game. 
2) if I run the game with patchwork_mk5v5.exe I have texture missed and I CAN't load my game (white screen).

**Comment by ezdiy** [comment]
Do not use mk5, use mk6 at the very least or preferably mk9. The load white screen bug was fixed long ago.

**Comment by emris93** [comment]
Hello, I tested with MK9 and MK6 and I have always the load white screen bug If a run the game with patchwork .exe but it's work if I launch directly the game without patchwork.

**Comment by ezdiy** [comment]
@emris93 I see. Does free-h and editor work? If so, that's a plugin compatibility or locale issue.

Enable [SPAM] checkbox in Advanced tab, and attach `Koikatu_Data\output_log.txt` right after the white screen appears.

If Free-H, editor and config screen doesnt work for you either, you might be using outdated copy of the game (pw needs 5/25 DLC).

Also, try disabling all the options under `Advanced->Performance` if that may help.

**Comment by emris93** [comment]
Hello, 
Free H doesn't works but charamaker works and my game is updated (05/25). I tested your solutions but nothing works.
here is the Output log : 
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2107617/output_log.txt)
and it's the unity console when I run the game : 
![unity](https://user-images.githubusercontent.com/40270055/41491789-ca41e10e-70ea-11e8-812f-ef463e73adf1.jpg)
maybe it can help.

**Comment by ezdiy** [comment]
Got white screen with the python console. I'll add compatibility for it, meanwhile you can just disable it.

**Comment by emris93** [comment]
How can I disable it ? Disable launcher ??

**Comment by ezdiy** [comment]
@emris93 By removing its dll file. Anyhow, added v3 and it seems to work with console now.

**Comment by emris93** [comment]
Finally it's work @ezdiy I can load save game. I'll do others tests if I find others problems I'll tell you that.
Thx very much dude :). I love you so much x).  
In fact, HS question: you were not in the discord koikatsu translation ? With Lucifer, NMX, BadOne ?

**Comment by ezdiy** [comment]
@emris93 

Patchwork is intentionally somewhat obscure for reasons you've experienced yourself - it's not really ready for public (I even posted a warning on discord you mentioned to that effect). Features (and ensuing bugs) are added too fast. There's an "official" betatester discord dedicated solely to this at https://discord.gg/rH5Knf if you're interested in following progress of the mod.

**Comment by ezdiy** [comment]
fixed in v3
