### ISSUE TITLE
Koikatsu crash when starting a new game

### ISSUE THREAD

**Issue by myonmyuu** [kkdevs/Patchwork#7]
If I launch Koikatsu through the patchwork launcher, the game always crashes when trying to start a new game and gets stuck loading when attempting to load a save, even on a non-modded installation the launcher causes these problems, launching the game normally works fine.
When the game crashes, a Microsoft Visual C++ Runtime Library prompt is opened, the message is:
Runtime Error!

Program:           (is blank)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

The Evaluator says the following:
Trying to (re)load script env.
prettyprint.cs(58,13): warning CS0168: The variable `x' is declared but never used
Script environment initialized, 3 MonoBs running.
[unzip.Start] Done

Apart from that I was unable to find any logs, although I have both the [TRACE] and [SPAM] options enabled in the Logging settings

I have also tried the hardpatch, but had the same problems.

Thanks in advance for any help

**Comment by ezdiy** [comment]
Please post the log file from `Koikatu_Data\output_log.txt`

**Comment by myonmyuu** [comment]
Here's the original log.
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2133332/output_log.txt)
After removing the level13 file as the log mentioned, the game stopped crashing but instead got stuck at the following loading screen, the main menu music was still playing. 
The log afterwards:
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2133353/output_log.txt)
After removing the level8 file the game gets stuck in a black screen after the Illusion logo.
The log:
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2133369/output_log.txt)
After I added the files back and loaded the game normally, it was working without problems.

**Comment by ezdiy** [comment]
Level 8/13 most likely means you're missing a DLC (usually freeh and config section wont work either).

**Comment by myonmyuu** [comment]
Yes, I was missing the newest DLC  :/
Everything seems to work now, thank you for your help!

**Comment by 1waP2toxuw** [comment]
fixed
