### ISSUE TITLE
Characters turn invisible 

### ISSUE THREAD

**Issue by myonmyuu** [kkdevs/Patchwork#9]
When I launch Koikatsu through the launcher, even while using the default body files all of the characters turn invisible.
There aren't any problems if I launch the game regularly.

Using the custom uncensor feature I managed to get the males to be visible again but I can't get the females to work, I've also tried overwriting the original files and using sideloader uncensors, but It isn't working.
Other sideloader mods are working though.

Any help is appreciated

**Comment by ezdiy** [comment]
Here is how you troubleshoot mysterious issues like this in general, ordered by complexity:
* Post output log
* Could be a zipmod. Delete `userdata/mod` and untick `unzip` in scripts tab.
* Could be some other plugin/script. Uncheck all entries in scripts tab so pw runs alone.
* Could be launcher exe issue, try hardpatch
* Could be a card issue. Try using non-modded cards only. Theres currently no good checking in place when something is slightly wrong with a card, including missing mods. If one card trips, rest may fall like dominoes.
* If its a hardmod collision, you'll have to try with unmodded abdata

**Comment by myonmyuu** [comment]
Alright so It seems that whenever oo_base.unity3d isn't vanilla females turn invisible, haven't tried loading or even adding any cards and have installed the game from scratch to try to solve this.
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2152341/output_log.txt)
The log mentions not being able to load the file aswell...
At the time when that log was made I had oo_base.unity3d overwritten in abdata
I also tried the hardpatch, but there was no difference.
When I launch the game through the default exe the model is loaded as intended and here's the log if that might help
[output_log.txt](https://github.com/kkdevs/Patchwork/files/2152343/output_log.txt)

**Comment by ezdiy** [comment]
@myonmyuu Seems like after DLC update, sporadically some uncensors just don't work for some reason, though I managed to see it happen only once. After I deleted mod and csv folders it suddenly started working. Tested with futaboy unc straight replacing both oo and mm base, no custom path.

**Comment by myonmyuu** [comment]
Ah I see, that explains why everything except uncensors work... 
I've already tried a handful, might have to play without them for now, but thanks for the heads up.

**Comment by ezdiy** [comment]
try with v4, it may have fixed the issue.
also try Advanced->Performance and unchecking all options there.

**Comment by ezdiy** [comment]
should be fixed in mk12
